# Generated by Django 5.1.6 on 2025-02-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales_app", "0003_rename_product_type_producttype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="second_name",
            new_name="last_name",
        ),
    ]
